---
title: "Checkpoint 1: EDA"
subtitle: "By Arturo, Payson, and Victoria"
format: revealjs
slide-number: true
editor: visual
---

## Does healthcare access impact the number of preventable hospital stays of certain racial groups at the county level?

**Why this matters:**

-   Reduce preventable hospitalizations
-   Equitable resource allocation
-   Focus efforts where help is needed most

------------------------------------------------------------------------

## Data Overview

**Source: County Health Rankings 2025**

<<<<<<< HEAD
- “Ranks every county in each state on their Health Outcomes and Health Factors”

**Clinical Care**

- Preventable Hospital Stays (outpatient setting)
  - Providers (Primary Care, Physicans, Mental Health, Dentist)
  - Mammography Screening
  - Uninsured (Adults, Children)
=======
-   “Ranks every county in each state on their Health Outcomes and Health Factors”

**Clinical Care**

-   Preventable Hospital Stays (outpatient setting)
    -   Providers (Primary Care, Physicans, Mental Health, Dentist)
    -   Mammography Screening
    -   Uninsured (Adults, Children)
>>>>>>> 5546ef360ae741f9db4efff46ce7486dfa44a236

------------------------------------------------------------------------

## Preventable Hospitalizations by County

```{r, echo=FALSE}
source("Interactive_Map_Code.R")
```

## Regression Analysis of Racial Disparities in Preventable Hospital Stays

**Planned Approach:**

-   Outcome: Preventable hospital stays
-   Predictors: Uninsured rate, provider ratio, race group

**Modeling Strategy:**

-   Explore variable selection and regularization

------------------------------------------------------------------------

## Moving into modeling and interpretation

**Completed:**

-   Defined research question
-   Cleaned and preprocessed dataset
-   Created initial EDA visualizations

**Next Steps:**

-   Fit regression models
-   Interpret disparities and validate model
<<<<<<< HEAD
-   Create visual summaries and poster
=======
-   Create visual summaries and poster
>>>>>>> 5546ef360ae741f9db4efff46ce7486dfa44a236
